In [46]:
# Model from https://github.com/huggingface/pytorch-pretrained-BERT

# Test out pretrained bert in pytorch
import torch
from pytorch_pretrained_bert import TransfoXLTokenizer, TransfoXLModel, TransfoXLLMHeadModel
import fastText as ft
import os

In [79]:
# Load pre-trained model tokenizer (vocabulary)
en_vecs = ft.load_model(os.path.expanduser('~/FastData/wiki.en/wiki.en.bin'))


In [81]:
all_the_words = en_vecs.get_words()
word_dict = {}

for word in all_the_words:
    word_dict[word] = en_vecs.get_word_vector(word)

In [89]:
word_dict['li']

array([ 0.26141167,  0.34813213, -0.05342947, -0.02084644, -0.05338623,
       -0.00120144,  0.4341092 , -0.30513814, -0.22223756,  0.20207433,
        0.21684751, -0.09351014, -0.69343954, -0.1033778 , -0.16538183,
       -0.20132433, -0.09993681,  0.13594145,  0.02100542, -0.00512931,
        0.05699873,  0.024579  , -0.45615327,  0.05472073,  0.22832026,
        0.2558152 ,  0.74157274,  0.23695132, -0.4113443 ,  0.27284133,
       -0.47291553, -0.21937537,  0.20284161, -0.08161509, -0.3007961 ,
       -0.12052383,  0.2622432 ,  0.1344802 ,  0.14794438,  0.10920229,
       -0.43425828,  0.09011281,  0.4490866 , -0.08083284,  0.20428753,
        0.09732747, -0.2798313 ,  0.00630417,  0.15594643,  0.05798173,
        0.2516308 , -0.6360136 , -0.13983944,  0.07599242, -0.16891348,
        0.47035477,  0.20068254, -0.1449756 ,  0.08121951,  0.2453813 ,
        0.32354587, -0.49730414,  0.19002873,  0.04024819,  0.09717216,
        0.10950211, -0.04737526, -0.21580207, -0.3911832 , -0.29

In [41]:
# Extract the tokens for each word 
text = "My name is Seinfeld"
tokenized_text = tokenizer.tokenize(text)
print(tokenized_text)


indexed_tokens = tokenizer.convert_tokens_to_ids(tokenized_text)
print(indexed_tokens)

tokens_tensor = torch.tensor([indexed_tokens])
print(tokens_tensor)
# segments_ids = [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1]

# tokens_tensor = torch.tensor([indexed_tokens])
# segments_tensors = torch.tensor([segments_ids])
# print(tokens_tensor)
# print(segments_tensor)

['My', 'name', 'is', 'Seinfeld']
[1162, 237, 23, 16510]
tensor([[ 1162,   237,    23, 16510]])


In [13]:
# Load pre-trained model (weights)
model = BertModel.from_pretrained('bert-base-uncased')
model.eval()

tensor([[ 101, 2026, 2171, 2003, 7367, 2378, 8151, 1012,  102, 2054, 2003, 2115,
         2171, 1029]])


100%|██████████| 407873900/407873900 [02:13<00:00, 3055561.52B/s]


BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): BertLayerNorm()
    (dropout): Dropout(p=0.1)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0): BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): BertLayerNorm()
            (dropout): Dropout(p=0.1)
          )
        )
        (intermediate): BertIntermediate(
          (dense): Linear(in_features=768, out_features=3072, bias=True)
        )

In [29]:

# Predict hidden state for each token
with torch.no_grad():
    encoded_layers, _ = model(tokens_tensor, segments_tensors)
# We have a hidden states for each of the 12 layers in model bert-base-uncased
print(encoded_layers[1].shape)

torch.Size([1, 14, 768])


In [33]:
print(encoded_layers[0].shape)

torch.Size([1, 14, 768])
